name: PR Checker - Description, Task, Demo
description: Validates PR description for required sections.

inputs:
  pr-body:
    description: PR body content to validate
    required: false
    default: ""

runs:
  using: node20
  main: dist/index.js

branding:
  icon: clipboard
  color: green
